# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: "24.8.0"
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.380
    hooks:
    - id: pyright
      name: pyright (system)
      description: 'pyright static type checker'
      entry: pyright
      language: system
      'types_or': [python, pyi]
      require_serial: true
      minimum_pre_commit_version: '2.9.2'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ui\/.*$ # files in javascript folder
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0 # for some reasons, 8.57.0 has not been published
    hooks:
      - id: eslint
        types: [file]
        files: ui\/.*(?:\.[jt]sx?|\.vue)$ # *.js, *.jsx, *.ts, *.tsx, *.vue in ui/src folder
        args:
          - --config
          - ui/.eslintrc.cjs
          - --no-ignore
