services:
  zimfarm-db:
    image: postgres:15.2-bullseye
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - zimfarm_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=zimfarm
      - POSTGRES_USER=zimfarm
      - POSTGRES_PASSWORD=zimpass
  zimfarm-api:
    image: ghcr.io/openzim/zimfarm-dispatcher:latest
    ports:
      - 127.0.0.1:8004:80
    environment:
      BINDING_HOST: 0.0.0.0
      JWT_SECRET: DH8kSxcflUVfNRdkEiJJCn2dOOKI3qfw
      POSTGRES_URI: postgresql+psycopg://zimfarm:zimpass@zimfarm-db:5432/zimfarm
      ALEMBIC_UPGRADE_HEAD_ON_START: "1"
      ZIMIT_USE_RELAXED_SCHEMA: "y"
    depends_on:
      - zimfarm-db
  zimfarm-ui:
    image: ghcr.io/openzim/zimfarm-ui:latest
    ports:
      - 127.0.0.1:8003:80
    environment:
      ZIMFARM_WEBAPI: http://localhost:8004/v1
    depends_on:
      - zimfarm-api
  zimit-api:
    build:
      dockerfile: Dockerfile-api
      context: ..
    volumes:
      - ../api/src/zimitfrontend:/usr/local/lib/python3.12/site-packages/zimitfrontend
      - ../locales:/locales
    command:
      - uvicorn
      - zimitfrontend.entrypoint:app
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --reload
      - --reload-dir
      - /usr/local/lib/python3.12/site-packages/zimitfrontend
    ports:
      - 127.0.0.1:8002:80
    environment:
      INTERNAL_ZIMFARM_WEBAPI: http://zimfarm-api:80/v1
      _ZIMFARM_USERNAME: admin
      _ZIMFARM_PASSWORD: admin
      TASK_WORKER: worker
      HOOK_TOKEN: a_very_secret_token
      CALLBACK_BASE_URL: http://zimit-api:80/api/v1/requests/hook
    depends_on:
      - zimfarm-api
  zimit-ui-dev:
    build:
      dockerfile: dev/zimit_ui_dev/Dockerfile
      context: ..
    volumes:
      - ../ui/src:/app/src
      - ../locales:/locales
      - ../dev/zimit_ui_dev/config.json:/app/public/config.json
    ports:
      - 127.0.0.1:8001:80
    depends_on:
      - zimit-api
  zimit-ui-prod:
    build:
      dockerfile: Dockerfile-ui
      context: ..
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - zimit-api

volumes:
  zimfarm_data:
